// CommonJS, every file is module (by defualt)
// Modules - Encapsulated code (only share minimum)
const names = require("./4-firstModule")
// const {john,peter} = require("./4-firstModule")
const sayHi = require("./5-secondModule")
const data = require("./6-alternative-module-flavour")
require("./7-mine-grenade")
sayHi("susan")
sayHi(names.john)
sayHi(names.peter)
